version: "3"
services:
  elasticsearch:
    image: blacktop/elasticsearch:latest
    networks:
      - app_net
    ports:
      - "9201:9200"
    restart: always
  web:
    image: nginx:stable-alpine
    networks:
      - app_net
    ports:
      - "8001:80"
    restart: always
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
  phpfpm:
    image: php:7.2-fpm-alpine3.7
    networks:
      - app_net
    restart: always
    volumes:
      - .:/app
      - ${FILE_LIST}:/app/list.txt:ro
networks:
  app_net:
